<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-WorkerService-67c41755-5d9a-4329-9a39-a91b488a8235</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="13.1.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3"/>
    </ItemGroup>
</Project>
